#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
DATA_TABLESPACE="tbs_${POSTGRES_DB}_d"
DATA_TABLESPACE_PATH="/var/lib/postgresql/data/pg_tblspc/${POSTGRES_DB}/tbs_${POSTGRES_DB}_d"

INDEX_TABLESPACE="tbs_${POSTGRES_DB}_i"
INDEX_TABLESPACE_PATH="/var/lib/postgresql/data/pg_tblspc/${POSTGRES_DB}/tbs_${POSTGRES_DB}_i"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres"  <<-EOSQL
  CREATE TABLESPACE $DATA_TABLESPACE LOCATION '$DATA_TABLESPACE_PATH';
  CREATE TABLESPACE $INDEX_TABLESPACE LOCATION '$INDEX_TABLESPACE_PATH';

  ALTER DATABASE ${POSTGRES_DB} SET TABLESPACE $DATA_TABLESPACE;

EOSQL