#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
USER_ADM="${POSTGRES_DB}_adm"
USER_APP="${POSTGRES_DB}_app"

ROLE_APP="RL_${POSTGRES_DB}_app"
ROLE_USR="RL_${POSTGRES_DB}_usr"
ROLE_AUD="RL_${POSTGRES_DB}_aud"
ROLE_DBA="RL_${POSTGRES_DB}_dba"


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
 
  CREATE USER $USER_ADM WITH PASSWORD '$DB_PASSWORD_ADM';
  CREATE SCHEMA $POSTGRES_DB AUTHORIZATION $USER_ADM;
   
  CREATE USER $USER_APP WITH PASSWORD '$DB_PASSWORD_APP';

  CREATE ROLE $ROLE_APP;
  CREATE ROLE $ROLE_USR;
  CREATE ROLE $ROLE_AUD;
  CREATE ROLE $ROLE_DBA;

  GRANT $ROLE_APP TO $USER_APP;
  GRANT USAGE ON SCHEMA $POSTGRES_DB TO $USER_APP;

  GRANT ALL ON TABLESPACE TBS_${POSTGRES_DB}_I TO $USER_ADM;

  DROP SCHEMA IF EXISTS public CASCADE;
  DROP DATABASE IF EXISTS postgres;
EOSQL